export const questions = [
  {
    "id": 1,
    "text_ar": "هل يوجد تشققات هيكلية واضحة في العناصر الإنشائية الرئيسية (أعمدة، جسور، بلاطات)؟",
    "text_en": "Are there visible structural cracks in main structural elements (columns, beams, slabs)?",
    "ex_ar": "التشققات الهيكلية قد تشير إلى ضعف في قدرة التحمل أو مشاكل في التصميم. يجب فحص عرض واتجاه التشقق.",
    "ex_en": "Structural cracks may indicate bearing capacity issues or design problems. Crack width and direction must be examined.",
    "reference_ar": "وفقاً لـ ACI 224R-01: التشققات أكبر من 0.3 ملم تتطلب تقييم فوري",
    "reference_en": "Per ACI 224R-01: Cracks exceeding 0.3mm require immediate assessment",
    "reference_link": "/references/aci-224r-cracks",
    "weight": 3
  },
  {
    "id": 2,
    "text_ar": "هل تم تصميم المبنى وفقاً لكود ACI 318 أو معيار إنشائي معتمد؟",
    "text_en": "Was the building designed according to ACI 318 or an approved structural code?",
    "ex_ar": "التصميم وفق الكود يضمن حدود أمان مناسبة في التسليح، القص، والعزوم. عدم الالتزام يزيد احتمالات الفشل الإنشائي.",
    "ex_en": "Code-compliant design ensures adequate safety factors in reinforcement, shear, and moments. Non-compliance increases structural failure probability.",
    "reference_ar": "وفقاً لـ ACI 318-19: يجب اتباع متطلبات التصميم الإنشائي للخرسانة المسلحة",
    "reference_en": "Per ACI 318-19: Structural design requirements for reinforced concrete must be followed",
    "reference_link": "/references/aci-318-design",
    "weight": 3
  },
  {
    "id": 3,
    "text_ar": "هل النظام الإنشائي منتظم (Regular) أم غير منتظم (Irregular) من الناحية المعمارية؟",
    "text_en": "Is the structural system regular or irregular from an architectural perspective?",
    "ex_ar": "عدم الانتظام المعماري (انحرافات في المحاور، فتحات كبيرة، كتل متدلية) يزيد من تأثير الأحمال الجانبية والتواء المبنى.",
    "ex_en": "Architectural irregularity (axis offsets, large openings, overhangs) increases lateral load effects and building torsion.",
    "reference_ar": "وفقاً لـ ASCE 7-16 الفصل 12: عدم الانتظام يتطلب تحليل خاص",
    "reference_en": "Per ASCE 7-16 Chapter 12: Irregularities require special analysis",
    "reference_link": "/references/asce-7-irregularity",
    "weight": 3
  },
  {
    "id": 4,
    "text_ar": "هل تظهر علامات تآكل الحديد (صدأ، تقشر الخرسانة الغطائية)؟",
    "text_en": "Are there signs of steel corrosion (rust, concrete cover spalling)?",
    "ex_ar": "تآكل الحديد يقلل مساحة المقطع الفعال للتسليح ويضعف قدرة العنصر على تحمل الأحمال. الصدأ يتوسع ويسبب تشققات إضافية.",
    "ex_en": "Steel corrosion reduces effective reinforcement cross-section and weakens load-bearing capacity. Rust expansion causes additional cracking.",
    "reference_ar": "وفقاً لـ ACI 222R-01: تآكل الحديد يشكل خطر على السلامة الإنشائية",
    "reference_en": "Per ACI 222R-01: Steel corrosion poses structural safety risks",
    "reference_link": "/references/aci-222r-corrosion",
    "weight": 3
  },
  {
    "id": 5,
    "text_ar": "هل توجد انحرافات أو ميول ملحوظة في الأعمدة أو الجدران الحاملة؟",
    "text_en": "Are there noticeable deflections or tilts in columns or load-bearing walls?",
    "ex_ar": "الانحرافات تشير إلى فشل محتمل في الأساسات، حمولة زائدة، أو مشاكل في الربط بين العناصر. يجب قياسها بدقة.",
    "ex_en": "Deflections indicate potential foundation failure, overloading, or connection problems. Accurate measurement is required.",
    "reference_ar": "وفقاً لـ ACI 318-19 الجدول 24.2.2: حدود الانحراف المسموح",
    "reference_en": "Per ACI 318-19 Table 24.2.2: Permissible deflection limits",
    "reference_link": "/references/aci-318-deflection",
    "weight": 3
  },
  {
    "id": 6,
    "text_ar": "هل تم إجراء فحوصات ميدانية للخرسانة (Core Test أو Schmidt Hammer)؟",
    "text_en": "Were field tests conducted on concrete (Core Test or Schmidt Hammer)?",
    "ex_ar": "الفحوصات الميدانية تؤكد مقاومة الخرسانة الفعلية في الموقع. بدونها، لا يمكن التأكد من جودة الخرسانة المنفذة.",
    "ex_en": "Field tests confirm actual in-situ concrete strength. Without them, executed concrete quality cannot be verified.",
    "reference_ar": "وفقاً لـ ACI 214.4R-10: أهمية فحص الخرسانة الميداني",
    "reference_en": "Per ACI 214.4R-10: Importance of field concrete testing",
    "reference_link": "/references/aci-214-testing",
    "weight": 2
  },
  {
    "id": 7,
    "text_ar": "هل تم تصميم المبنى لمقاومة الأحمال الزلزالية وفقاً للكود الزلزالي الأردني؟",
    "text_en": "Was the building designed to resist seismic loads per Jordanian Seismic Code?",
    "ex_ar": "الأردن يقع في منطقة زلزالية متوسطة. عدم مراعاة التصميم الزلزالي يزيد خطر الانهيار أثناء الهزات الأرضية.",
    "ex_en": "Jordan is in a moderate seismic zone. Ignoring seismic design increases collapse risk during earthquakes.",
    "reference_ar": "وفقاً للكود الزلزالي الأردني 2017: متطلبات التصميم المقاوم للزلازل",
    "reference_en": "Per Jordanian Seismic Code 2017: Earthquake-resistant design requirements",
    "reference_link": "/references/jordan-seismic-code",
    "weight": 3
  },
  {
    "id": 8,
    "text_ar": "هل يتوافق تسليح الأعمدة مع الحد الأدنى المطلوب (1% من مساحة المقطع)؟",
    "text_en": "Does column reinforcement meet minimum requirements (1% of cross-sectional area)?",
    "ex_ar": "الحد الأدنى للتسليح يضمن قدرة تحمل كافية ويمنع الفشل المفاجئ. نقص التسليح يؤدي إلى انهيار هش.",
    "ex_en": "Minimum reinforcement ensures adequate bearing capacity and prevents sudden failure. Insufficient reinforcement leads to brittle collapse.",
    "reference_ar": "وفقاً لـ ACI 318-19 البند 10.6.1.1: الحد الأدنى للتسليح الطولي في الأعمدة",
    "reference_en": "Per ACI 318-19 Section 10.6.1.1: Minimum longitudinal reinforcement in columns",
    "reference_link": "/references/aci-318-column-rebar",
    "weight": 3
  },
  {
    "id": 9,
    "text_ar": "هل تم توفير حديد قص (Stirrups/Ties) كافٍ في الأعمدة والجسور؟",
    "text_en": "Was adequate shear reinforcement (Stirrups/Ties) provided in columns and beams?",
    "ex_ar": "حديد القص يمنع فشل القص الهش ويحد من انتشار التشققات القطرية. نقصه يؤدي لانهيار مفاجئ بدون إنذار.",
    "ex_en": "Shear reinforcement prevents brittle shear failure and limits diagonal crack propagation. Its absence causes sudden collapse without warning.",
    "reference_ar": "وفقاً لـ ACI 318-19 الفصل 9: متطلبات القص في العناصر الإنشائية",
    "reference_en": "Per ACI 318-19 Chapter 9: Shear requirements in structural members",
    "reference_link": "/references/aci-318-shear",
    "weight": 3
  },
  {
    "id": 10,
    "text_ar": "هل توجد مناطق حرجة (Plastic Hinges) تم تصميمها بشكل مطابق للكود الزلزالي؟",
    "text_en": "Are critical regions (Plastic Hinges) designed per seismic code requirements?",
    "ex_ar": "المفاصل اللدنة تتشكل أثناء الزلازل. تصميمها الصحيح يتطلب حديد عرضي كثيف (Confinement) لتحسين قابلية التشوه.",
    "ex_en": "Plastic hinges form during earthquakes. Proper design requires dense transverse reinforcement (Confinement) for ductility improvement.",
    "reference_ar": "وفقاً لـ ACI 318-19 الفصل 18: التصميم الزلزالي للعناصر الإنشائية",
    "reference_en": "Per ACI 318-19 Chapter 18: Seismic design of structural members",
    "reference_link": "/references/aci-318-seismic",
    "weight": 3
  },
  {
    "id": 11,
    "text_ar": "هل تم فحص مقاومة الثقب (Punching Shear) حول الأعمدة في البلاطات المسطحة؟",
    "text_en": "Was punching shear resistance checked around columns in flat slabs?",
    "ex_ar": "فشل الثقب هو الأخطر في البلاطات المسطحة وقد يحدث بشكل مفاجئ. يتطلب تحقق دقيق من الإجهادات حول الأعمدة.",
    "ex_en": "Punching failure is most critical in flat slabs and may occur suddenly. Requires precise stress verification around columns.",
    "reference_ar": "وفقاً لـ ACI 318-19 البند 22.6: تصميم مقاومة الثقب",
    "reference_en": "Per ACI 318-19 Section 22.6: Punching shear design",
    "reference_link": "/references/aci-318-punching",
    "weight": 3
  },
  {
    "id": 12,
    "text_ar": "هل تمت مراعاة طول التثبيت (Development Length) للحديد في الوصلات؟",
    "text_en": "Was development length considered for reinforcement in connections?",
    "ex_ar": "طول التثبيت غير الكافي يمنع انتقال الإجهادات بشكل كامل ويسبب انزلاق الحديد، مما يقلل من قدرة التحمل.",
    "ex_en": "Insufficient development length prevents full stress transfer and causes steel slippage, reducing bearing capacity.",
    "reference_ar": "وفقاً لـ ACI 318-19 الفصل 25: طول التثبيت والوصلات",
    "reference_en": "Per ACI 318-19 Chapter 25: Development length and splices",
    "reference_link": "/references/aci-318-development",
    "weight": 3
  },
  {
    "id": 13,
    "text_ar": "هل غطاء الخرسانة (Concrete Cover) كافٍ ومطابق للبيئة المحيطة؟",
    "text_en": "Is concrete cover adequate and suitable for the surrounding environment?",
    "ex_ar": "الغطاء غير الكافي يعرض الحديد للتآكل السريع، خاصة في بيئات رطبة أو ساحلية، مما يقلل العمر الافتراضي بشكل كبير.",
    "ex_en": "Insufficient cover exposes steel to rapid corrosion, especially in humid or coastal environments, significantly reducing service life.",
    "reference_ar": "وفقاً لـ ACI 318-19 الجدول 20.6.1.3.1: الحد الأدنى للغطاء الخرساني",
    "reference_en": "Per ACI 318-19 Table 20.6.1.3.1: Minimum concrete cover requirements",
    "reference_link": "/references/aci-318-cover",
    "weight": 2
  },
  {
    "id": 14,
    "text_ar": "هل وصلات الجسور مع الأعمدة (Beam-Column Joints) مصممة لتحمل الأحمال الزلزالية؟",
    "text_en": "Are beam-column joints designed to withstand seismic loads?",
    "ex_ar": "الوصلات هي المناطق الأكثر حرجاً أثناء الزلازل. فشلها يسبب انهيار تدريجي للمبنى. تحتاج حديد عرضي كثيف وتفصيل دقيق.",
    "ex_en": "Joints are most critical areas during earthquakes. Their failure causes progressive building collapse. Dense transverse reinforcement and precise detailing required.",
    "reference_ar": "وفقاً لـ ACI 318-19 البند 18.8: متطلبات وصلات الجسور والأعمدة",
    "reference_en": "Per ACI 318-19 Section 18.8: Beam-column joint requirements",
    "reference_link": "/references/aci-318-joints",
    "weight": 3
  },
  {
    "id": 15,
    "text_ar": "هل تم حساب الانفعال والانحناء (Deflection) وهل يقع ضمن الحدود المسموحة؟",
    "text_en": "Was deflection calculated and is it within permissible limits?",
    "ex_ar": "الانحناء الزائد يسبب تشققات في الجدران، تلف في التشطيبات، ومشاكل وظيفية. يجب ألا يتجاوز L/240 للأحمال الحية.",
    "ex_en": "Excessive deflection causes wall cracks, finish damage, and functional issues. Should not exceed L/240 for live loads.",
    "reference_ar": "وفقاً لـ ACI 318-19 الجدول 24.2.2: حدود الانحراف المسموح",
    "reference_en": "Per ACI 318-19 Table 24.2.2: Permissible deflection limits",
    "reference_link": "/references/aci-318-deflection-limits",
    "weight": 2
  },
  {
    "id": 16,
    "text_ar": "هل تم توزيع الجدران القصية (Shear Walls) بشكل متناظر في المبنى؟",
    "text_en": "Are shear walls distributed symmetrically in the building?",
    "ex_ar": "التوزيع غير المتناظر للجدران القصية يسبب التواء المبنى أثناء الزلازل، مما يزيد الأضرار في الأطراف البعيدة عن مركز الصلابة.",
    "ex_en": "Asymmetric shear wall distribution causes building torsion during earthquakes, increasing damage at edges far from stiffness center.",
    "reference_ar": "وفقاً لـ ASCE 7-16 البند 12.8.4: متطلبات التناظر في النظام الإنشائي",
    "reference_en": "Per ASCE 7-16 Section 12.8.4: Structural system symmetry requirements",
    "reference_link": "/references/asce-7-symmetry",
    "weight": 3
  },
  {
    "id": 17,
    "text_ar": "هل تم اعتبار أحمال الرياح (Wind Loads) في التصميم الإنشائي؟",
    "text_en": "Were wind loads considered in structural design?",
    "ex_ar": "أحمال الرياح مهمة في المباني العالية والمكشوفة. عدم احتسابها يزيد الانحناء الجانبي والاهتزازات.",
    "ex_en": "Wind loads are important in tall and exposed buildings. Ignoring them increases lateral drift and vibrations.",
    "reference_ar": "وفقاً لـ ASCE 7-16 الفصل 26-30: حساب أحمال الرياح",
    "reference_en": "Per ASCE 7-16 Chapters 26-30: Wind load calculations",
    "reference_link": "/references/asce-7-wind",
    "weight": 2
  },
  {
    "id": 18,
    "text_ar": "هل تم تصميم الأساسات بناءً على تقرير جيوتقني (Soil Report)؟",
    "text_en": "Were foundations designed based on a geotechnical report (Soil Report)?",
    "ex_ar": "تقرير التربة ضروري لتحديد قدرة التحمل والهبوطات المتوقعة. بدونه، قد تحدث هبوطات تفاضلية تسبب تشققات هيكلية.",
    "ex_en": "Soil report is essential for determining bearing capacity and expected settlements. Without it, differential settlements may cause structural cracks.",
    "reference_ar": "وفقاً لـ ACI 318-19 الفصل 13: متطلبات تصميم الأساسات",
    "reference_en": "Per ACI 318-19 Chapter 13: Foundation design requirements",
    "reference_link": "/references/aci-318-foundations",
    "weight": 3
  },
  {
    "id": 19,
    "text_ar": "هل يوجد إشراف هندسي متخصص أثناء التنفيذ؟",
    "text_en": "Was there specialized engineering supervision during construction?",
    "ex_ar": "الإشراف الهندسي يضمن تنفيذ التصميم بدقة، ويكتشف الأخطاء مبكراً. غيابه يزيد احتمالات العيوب الإنشائية.",
    "ex_en": "Engineering supervision ensures accurate design implementation and early error detection. Its absence increases structural defect probability.",
    "reference_ar": "وفقاً لـ ACI 318-19 الفصل 26: متطلبات التفتيش والإشراف",
    "reference_en": "Per ACI 318-19 Chapter 26: Inspection and supervision requirements",
    "reference_link": "/references/aci-318-supervision",
    "weight": 2
  },
  {
    "id": 20,
    "text_ar": "هل تم صب الخرسانة في ظروف جوية مناسبة (حرارة، رطوبة)؟",
    "text_en": "Was concrete poured in suitable weather conditions (temperature, humidity)?",
    "ex_ar": "الصب في حرارة عالية أو منخفضة جداً يؤثر على مقاومة الخرسانة وقد يسبب تشققات حرارية. المعالجة الصحيحة ضرورية.",
    "ex_en": "Pouring in extreme temperatures affects concrete strength and may cause thermal cracks. Proper curing is essential.",
    "reference_ar": "وفقاً لـ ACI 305R-10 و ACI 306R-16: متطلبات الصب في الأجواء الحارة والباردة",
    "reference_en": "Per ACI 305R-10 & ACI 306R-16: Hot and cold weather concreting requirements",
    "reference_link": "/references/aci-305-306-weather",
    "weight": 2
  },
  {
    "id": 21,
    "text_ar": "هل تم استخدام مواد ذات جودة معتمدة (أسمنت، حصى، رمل، حديد)؟",
    "text_en": "Were approved quality materials used (cement, gravel, sand, steel)?",
    "ex_ar": "جودة المواد تؤثر مباشرة على مقاومة ومتانة الخرسانة. استخدام مواد غير مطابقة يقلل العمر الافتراضي ويزيد المخاطر.",
    "ex_en": "Material quality directly affects concrete strength and durability. Using non-compliant materials reduces service life and increases risks.",
    "reference_ar": "وفقاً لـ ACI 318-19 الفصل 20 و 26: متطلبات جودة المواد",
    "reference_en": "Per ACI 318-19 Chapters 20 & 26: Material quality requirements",
    "reference_link": "/references/aci-318-materials",
    "weight": 2
  },
  {
    "id": 22,
    "text_ar": "هل تم التحقق من تفاصيل التسليح (Lap Splices) وأطوال الربط؟",
    "text_en": "Were reinforcement details (Lap Splices) and lap lengths verified?",
    "ex_ar": "أطوال الربط غير الكافية تؤدي لانزلاق القضبان وفقدان الاستمرارية في نقل الإجهادات، مما يضعف العنصر بشكل كبير.",
    "ex_en": "Insufficient lap lengths cause bar slippage and loss of continuity in stress transfer, significantly weakening the member.",
    "reference_ar": "وفقاً لـ ACI 318-19 البند 25.5: متطلبات وصلات التسليح",
    "reference_en": "Per ACI 318-19 Section 25.5: Reinforcement splice requirements",
    "reference_link": "/references/aci-318-splices",
    "weight": 2
  },
  {
    "id": 23,
    "text_ar": "هل توجد فتحات كبيرة (مصاعد، سلالم) تم تدعيمها بشكل مناسب؟",
    "text_en": "Are large openings (elevators, stairs) properly reinforced?",
    "ex_ar": "الفتحات تقطع مسار القوى الطبيعي وتحتاج تسليح إضافي حول الحواف. إهمال ذلك يسبب تشققات قطرية حادة.",
    "ex_en": "Openings interrupt natural force path and require additional edge reinforcement. Neglecting this causes severe diagonal cracks.",
    "reference_ar": "وفقاً لـ ACI 318-19 البند 8.7: متطلبات الفتحات في البلاطات",
    "reference_en": "Per ACI 318-19 Section 8.7: Slab opening requirements",
    "reference_link": "/references/aci-318-openings",
    "weight": 3
  },
  {
    "id": 24,
    "text_ar": "هل تم حساب تأثير الزحف والانكماش (Creep & Shrinkage) على الانحناء طويل الأمد؟",
    "text_en": "Were creep and shrinkage effects on long-term deflection calculated?",
    "ex_ar": "الزحف والانكماش يزيدان الانحناء مع الزمن، خاصة في البلاطات ذات الحمولة المستمرة. يجب احتسابهما لتجنب التشوهات المفرطة.",
    "ex_en": "Creep and shrinkage increase deflection over time, especially in continuously loaded slabs. Must be calculated to avoid excessive deformations.",
    "reference_ar": "وفقاً لـ ACI 318-19 البند 24.2.4: تأثير الزحف والانكماش",
    "reference_en": "Per ACI 318-19 Section 24.2.4: Creep and shrinkage effects",
    "reference_link": "/references/aci-318-creep",
    "weight": 2
  },
  {
    "id": 25,
    "text_ar": "هل تم تطبيق الشروط الخاصة للخرسانة المعرضة للكبريتات أو الكلوريدات؟",
    "text_en": "Were special requirements for concrete exposed to sulfates or chlorides applied?",
    "ex_ar": "البيئات العدوانية (تربة كبريتية، مياه مالحة) تتطلب نوع خاص من الأسمنت وغطاء إضافي لمنع التدهور السريع.",
    "ex_en": "Aggressive environments (sulfate soil, saltwater) require special cement type and additional cover to prevent rapid deterioration.",
    "reference_ar": "وفقاً لـ ACI 318-19 الجدول 19.3.2.1: متطلبات التعرض للكبريتات",
    "reference_en": "Per ACI 318-19 Table 19.3.2.1: Sulfate exposure requirements",
    "reference_link": "/references/aci-318-sulfate",
    "weight": 2
  }
];
